package com.github.thibseisel.kdenticon

import com.github.thibseisel.kdenticon.rendering.*
import java.io.File
import java.io.OutputStream
import java.security.MessageDigest

/**
 * An icon made of simple shapes generated from a hash sequence.
 *
 * Identicons are generally used as placeholder images for user that don't have an avatar.
 * If the same sequence is used to create the icon, then the icon's look will be the same.
 *
 * There are 3 components used to generate an Identicon:
 *
 * - [Renderer] indicates where and how the icon should be drawn.
 * - [IconGenerator] describes the generation algorithm and the available shapes.
 * One could extend this class to define their own shapes and their position in the icon's grid.
 * - [IdenticonStyle] defines parameters that alters the icon's general look such as color and padding.
 *
 * Most common cases such as saving as PNG or SVG are covered by methods [saveToPngFile]
 * and [saveAsSvg]. If you'd like to use your own implementation of [Renderer], you should pass it
 * to the [draw] method.
 *
 * @constructor Creates a new icon of a given size with the given hash sequence, initialized with
 * default generator and style.
 *
 * While the hash sequence could be anything (calculated from a string, generated by a calculation,
 * queried from storage or network), make sure not to use sensitive information such as password
 * or auth token.
 *
 * @param hash The byte sequence to use as base to generate this icon.
 * There should be at least 6 bytes.
 * @param size The size of this icon in pixels.
 *
 */
@Suppress("unused", "MemberVisibilityCanPrivate")
class Identicon(val hash: ByteArray, val size: Int) {

    init {
        require(hash.size > 5) { "The hash should be composed at least of 6 bytes." }
        require(size > 0) { "The size should be 1 pixel or larger." }
    }

    /**
     * The generator used to render this icon.
     *
     * This will be an instance of [IconGenerator] by default.
     * Clients may extends the existing [IconGenerator] class and set it to this icon
     * to provide their own custom shapes.
     */
    var generator = IconGenerator()

    /**
     * The style for this icon.
     * This dictates what kind of colors use when generating this icon.
     *
     * This is initialized to the [default style][IdenticonStyle.DEFAULT_STYLE].
     */
    var style = IdenticonStyle.DEFAULT_STYLE

    /**
     * Draws this icon using the specified renderer.
     *
     * This method is intended for usage with custom renderers.
     * A custom renderer could for example render an identicon is a file format not natively supported by KDenticon.
     *
     * @param renderer The renderer used to render this icon.
     * @param rect The bounds of the rendered icon. No padding will be applied to the rectangle.
     */
    fun draw(renderer: Renderer, rect: Rectangle) {
        generator.generate(renderer, rect, style, hash)
    }

    /**
     * Get the bounds of the icon, taking its padding into account.
     */
    fun getIconBounds() = Rectangle(
            (style.padding * size).toInt(),
            (style.padding * size).toInt(),
            size - (style.padding * size).toInt() * 2,
            size - (style.padding * size).toInt() * 2
    )

    /**
     * Save this icon to a PNG file.
     * This internally uses [PngRenderer].
     *
     * Notice: do not use this method, as the PngRenderer is not ready.
     *
     * @param stream
     */
    fun saveToPngFile(stream: OutputStream) {
        val renderer = PngRenderer(size, size)
        val iconBounds = this.getIconBounds()
        this.draw(renderer, iconBounds)
        renderer.savePng(stream)
    }

    /**
     * Save this icon to an SVG file.
     * This internally uses a [SvgRenderer].
     *
     * @param filepath path of the file to create.
     * Callers are responsible for adding the `.svg` file extension if desired.
     */
    fun saveToSvgFile(filepath: String) {
        File(filepath).outputStream().use {
            saveAsSvg(it)
        }
    }

    /**
     * Renders this icon as a SVG file to be sent by the given stream.
     * Most of the time you'd want to save this icon to a file; in this case, prefer using
     * [saveToSvgFile].
     *
     * Callers are responsive for closing the passed stream.
     *
     * @param stream The stream on which SVG instructions should be sent.
     */
    fun saveAsSvg(stream: OutputStream) {
        val renderer = SvgRenderer(size, size)
        draw(renderer, getIconBounds())
        stream.bufferedWriter().use {
            renderer.save(it, false)
        }
    }

    companion object {

        /**
         * Creates an identicon from a specified hash.
         *
         * @param hash The hash tha will be used as base for this icon.
         * The hash must contain at least 6 bytes.
         * @param size The width and height or the icon in pixels.
         * The size must be a strictly positive number.
         * @return An identicon instance
         */
        @JvmStatic fun fromHash(hash: ByteArray, size: Int): Identicon = Identicon(hash, size)

        /**
         * Generates a hash from a specified value and creates an Identicon instance from the generated hash.
         * The hash is produced from the string representation of the provided `value` hashed by the SHA-1 algorithm.
         *
         * @param value An object to use as basis to generate the hash
         * @param size The width and height of the icon in pixels.
         * The size must be a strictly positive number.
         * @return An identicon instance
         */
        @JvmStatic fun fromValue(value: Any, size: Int): Identicon {
            val sha1 = MessageDigest.getInstance("SHA-1")
            sha1.update(value.toString().toByteArray())
            return Identicon(sha1.digest(), size)
        }
    }
}